name: deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # - name: checkout-code
      #   uses: actions/checkout@v4

      # - name: setup node
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 20

      # - name: add pnpm
      #   uses: pnpm/action-setup@v4
      #   with:
      #     version: 9

      # - name: build frontend
      #   run: |
      #     cd "./frontend"
      #     pnpm install --frozen-lockfile
      #     pnpm run build

      # - name: build backend
      #   run: |
      #     cd "./backend"
      #     pnpm install --frozen-lockfile
      #     pnpm run build

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.HOST_ADDRESS }}
          EC2_USER: ${{ secrets.HOST_MACHINE }}
          EC2_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "${EC2_KEY}" > ec2-key.pem
          chmod 600 ec2-key.pem
          ssh -o StrictHostKeyChecking=no -i ec2-key.pem $EC2_USER@$EC2_HOST
